include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
    - linter

linter:
  rules:
    - camel_case_types

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - integration_test/**
    - test_driver/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  rules-exclude:
    - test/**
    - integration_test/**
    - test_driver/**
  anti-patterns:
    - long-method
    - long-parameter-list